services:
  php:
    build: ./docker/php
    container_name: sms_alert
    working_dir: /var/www
    volumes:
      - .:/var/www:delegated
      - ./docker/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - database
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgresql://app:app@database:5432/app
    ports:
      - "9000:80"

  database:
    image: postgres:16
    container_name: sms_alert_db
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: sms_alert_adminer
    depends_on:
      - database
    environment:
      - APP_ENV=dev
      - ADMINER_DESIGN=pepa-linha
      - ADMINER_DEFAULT_SERVER=database
    restart: always
    ports:
      - "8081:8080"

volumes:
  database_data:
